### ISSUE TITLE
Update DC2 tutorial notebooks with new datasets (Run2.1i)

### ISSUE THREAD

**Issue by cnsetzer** [LSSTDESC/DC2-analysis#110]
Initiated at the DESC Paris 2019 Hack Day, we are replacing the tutorial notebooks with datasets from `Run2.1i`.

To avoid duplicate work, in case others are replacing the datasets, I will begin with the `object_gcr...` notebooks. If getting to additional ones after or during the hack, I will comment here which those are that I am updating.

To make the updates easier I will include a checklist:

- [ ] `dia_sn_vs_truth.ipynb`
- [ ] `dia_source_object_stamp.ipynb`
- [ ] `dm_butler_lensing_cuts.ipynb`
- [ ] `dm_butler_postage_stamps.ipynb`
- [x] `dm_butler_skymap.ipynb`
- [x] `extragalactic_gcr_cluster_colors.ipynb`
- [x] `extragalactic_gcr_cluster_members.ipynb`
- [x] `extragalactic_gcr_hod.ipynb`
- [x] `extragalactic_gcr_mass_relations.ipynb`
- [x] `extragalactic_gcr_redshift_dist.ipynb`
- [ ] `matching_fof.ipynb`
- [ ] `matching_stack.ipynb`
- [x] `object_gcr_1_intro.ipynb`
- [x] `object_gcr_2_lensing_cuts.ipynb`
- [x] `object_gcr_3_challeneges.ipynb`
- [ ] `object_gcr_4_photoz.ipynb`
- [ ] `object_pandas_stellar_locus.ipynb`
- [ ] `object_per_visit_postage_stamp.ipynb`
- [ ] `object_spark_1_intro.ipynb`
- [ ] `postgres_forcedsource.ipynb`
- [ ] `postgres_object_1_intro.ipynb`
- [ ] `postgres_object_2.ipynb`
- [ ] `truth_gcr_intro.ipynb`
- [ ] `truth_gcr_variables.ipynb`

**Comment by cnsetzer** [comment]
Here I am making note of the tutorial notebooks which need GCRcatalogs, that are not currently available, to be updated:
- `object_gcr_4_photoz.ipynb` needs `dc2_object_run2.1i_with_photoz`
- `dia_sn_vs_truth.ipynb` needs `dc2_truth_run2.1_variable_summary`,`dc2_truth_run2.1_variable_lightcurve`, `dc2_dia_source_run2.1i_test`, `dc2_dia_object_run2.1i_test`
-`dia_source_object_stamp.ipynb` needs `dc2_dia_source_run2.1i_test` and `dc2_dia_object_run2.1i_test`
-`matching_fof.ipynb` needs `dc2_truth_run2.1_static`

*will continue to update as I continue through more notebooks*

**Comment by yymao** [comment]
Partly fixed by #113, and superseded by #130.
