### ISSUE TITLE
Feedback for notebook comparing observational and galaxy properties for DC2

### ISSUE THREAD

**Issue by nehapjoshi** [LSSTDESC/DC2-analysis#112]
I've created a notebook that can be used with Run 1.2i, 1.2p, or 2.1i to analyze the relationships between observational and galaxy properties.  It is located in the branch u/npjoshi/validation-notebooks under contributed, named Observation_vs_galaxy.  Please take a look at it and give me any feedback regarding additional tests that can be included or anything else that would be useful.  Thanks!

direct link: https://github.com/LSSTDESC/DC2-analysis/blob/u/npjoshi/validation-notebooks/contributed/Observation_vs_galaxy.ipynb

**Comment by yymao** [comment]
@nehapjoshi do you want to submit a Pull Request for your notebook so that we can assign a reviewer?

**Comment by nehapjoshi** [comment]
At the moment, the notebook isn't ready for review to be incorporated into the master branch.  Rachel and I were hoping to get some general feedback about other tests that would be good to run and show that a galaxy property is (hopefully) independent of observational properties, in addition to ones already included using properties like PSF FWHM and ellipticity of PSF against colors and magnitude.

@fjaviersanchez when Rachel and I had asked about next steps for this notebook you had indicated that I should put it up here. Are there any other steps that would be appropriate?

**Comment by fjaviersanchez** [comment]
Thanks @nehapjoshi! The tests in your notebook look good to me. I'll take another look and check if I can come up with something else. @kadrlica and @rmjarvis may have some feedback so I'm pinging them here. One thing that can be useful is to prepare this notebook for review and add other tests in a second version (or a second notebook). What do you think?

**Comment by rmandelb** [comment]
We'd like to do whatever is most useful - if there are obvious tests to add based on an initial look, we thought it might be best to do before the initial review.  But if not, then we can indeed prepare it for review now.  Neha, let's discuss this when we meet today.

**Comment by fjaviersanchez** [comment]
I think that now that we closed #117 we can close this as well. Please, feel free to reopen if you think it'll be helpful. Thanks for submitting the notebook @nehapjoshi!
