### ISSUE TITLE
Update tutorials for 2020 July Meeting

### ISSUE THREAD

**Issue by yymao** [LSSTDESC/DC2-analysis#130]
@katrinheitmann (on behalf of 2020 July Meeting SOC) brought up the idea of a DC tutorial session at the (virtual) meeting. To prepare for that, we should update the [tutorials in this repo](https://github.com/LSSTDESC/DC2-analysis/tree/master/tutorials#dc2-tutorials), and add new ones if people are interested in contributing.  

Let's use this issue for high-level discussion and Q&A about this tutorial update campaign. Later, we can open additional issues for specific tasks. 

The majority of work would be updating all the tutorial notebooks that still use Run 1.x object catalogs, truth catalogs (note that Run 1.x truth catalog format is now deprecated), and associated add-ons (photo-z and matched catalog). 

Depending how much human power we can obtain, we may want to add tutorial notebooks on several new topics, including: metacal, photo-z for cosmoDC2, static truth summary catalog, and matching object catalog with cosmoDC2.
 
cc @heather999 @johannct @JoanneBogart @wmwv @slosar @reneehlozek @EiffL @fjaviersanchez @evevkovacs

**Comment by heather999** [comment]
To do list for this Friday's Hack Session

- [ ] Announce on #desc-dc2
- [ ] Confirm data availability from DR6 and DR3 
    - [ ] DR6 calexps will be available at NERSC by June 4th
    - [ ] transfer completed tracts/patches of coadds/multiband/object catalogs
- [ ] Properly record all known “features” of available Run2.2i data [on Confluence](https://confluence.slac.stanford.edu/display/LSSTDESC/DESC+DRP+DC2+Run2.2i+Processing)
- [ ] Review the existing Confluence pages
    - [ ] [DC2 Data Product Overview ](https://confluence.slac.stanford.edu/display/LSSTDESC/DC2+Data+Product+Overview)
    - [ ] [DC2 Tutorial](https://confluence.slac.stanford.edu/display/LSSTDESC/DC2+Tutorial%3A+A+Step-by-step+Guide)
    - [ ] [Using Jupyter At NERSC](https://confluence.slac.stanford.edu/display/LSSTDESC/Using+Jupyter+at+NERSC)
- [ ] Check if any PRs in GCRCatalogs should be merged.
    - [ ] Make sure all new data products have been copied to shared/
    - [ ] Make a new release of GCRCatalogs if possible.
- [ ] Make sure DESC Kernels are up to date
    - [ ] Install the newly tagged GCRCatalogs. If a tagged version is not available, install the master branch to desc-python-dev.
- [ ] Review contents of https://github.com/LSSTDESC/desc-dc2-dm-data
- [ ] Try a test run of current DC2-Analysis tutorials using the current desc-python and desc-stack
- [ ] Make a list of tutorial notebooks / documentation that we want to update
    - [ ] Assign each task to one person so that people know what to work on

**Comment by yymao** [comment]
Thanks @heather999 --- a very nice (and long, oops!) list.  What's the best way to distribute the work. And should we recruit a few people to help out?

**Comment by heather999** [comment]
Hi @yymao There is a lot to do....  
I'm working with Johann and Fabio to get whatever DR6 data we can over to NERSC, see: https://github.com/LSSTDESC/ImageProcessingPipelines/issues/133#issuecomment-637815814

I'd like to clarify the "features" of DR3 and DR6 at the DESC DM tomorrow.

Any eyes that can help go over the Confluence pages would be helpful.  I will take another look too.

I'll leave it to you and Joanne to deal with GCRCatalogs and let me know if we need an updated release included in the kernels.

The desc-dc2-dm-data - we should both take a look at.  

One thing that would be nice to set up (maybe on Friday) is scheduled beavis-ci runs against at NERSC.  In the meantime, we'll have to do that by hand to see where DC2-Analysis stands.  I wouldn't get to that until at least tomorrow.

If you or others could make a list of tutorials/doc you already know need updating - it'd be great to get that started.

**Comment by yymao** [comment]
Thanks @heather999. 

I've gone through the DC2 Data Product Overview Conflunce page so I'll check it from the to-do list, but others are of course welcome to give it another look. I'll review the other Conflunce pages too. 

I'll work with Joanne on GCRCatalogs. We also need to copy Eli's redmapper catalog to /share. Let me ping Eli again. 

I took a look at `desc-dc2-dm-data` and it looks fine to me (except if we want to add DR6). Any other particular issues on your mind? 

I'll start to think about tutorials/doc that need update.

**Comment by yymao** [comment]
On "DC2 Tutorial: A Step-by-step Guide" -- I think the content is mostly up-to-date. Two minor issues that I noticed are:
1. Maybe should mention NERSC now requirs MFA
2. I think we have a `jupyter-debug.sh` script in some DESC space? It's ok to keep pointing to mine, but I thought I'd check. 

 
(Sorry, I realize GitHub is not the best place to quick iteration. If I should move this somewhere else, let me know.)

**Comment by yymao** [comment]
A (may be incomplete) list of notebooks that need to be updated
- [ ] object_gcr_1_intro.ipynb
- [ ] object_gcr_2_lensing_cuts.ipynb
- [ ] object_gcr_3_challenges.ipynb
- [ ] object_gcr_4_photoz.ipynb
- [ ] object_pandas_stellar_locus.ipynb
- [ ] object_per_visit_postage_stamp.ipynb
- [ ] matching_fof.ipynb
- [ ] matching_stack.ipynb
- [ ] truth_gcr_intro.ipynb
- [ ] truth_gcr_variables.ipynb

**Comment by heather999** [comment]
@yymao I'm certainly happy to continue discussing the Confluence pages on the #desc-dc2-data-access channel. In the meantime, I've updated https://confluence.slac.stanford.edu/display/LSSTDESC/DC2+Tutorial%3A+A+Step-by-step+Guide to provide some links to update passwords and Muti Factor Authentication.

I think I'll add your `jupyter-debug.sh` to the desc-python repo which manages the kernels and just install it that way so it's under `/global/common/software/lsst/common/miniconda/` or something like that - then update the Confluence page.

**Comment by heather999** [comment]
@yymao In `desc-dc2-dm-data` I want to move off using CSCRATCH where possible and use CFS - starting with the data I know we want to utilize in the short term for the tutorials. I'm assuming some tutorials may continue to point to Run2.1 for now until DR6 is more fully available, for example.  And I'm wondering about 1.2x, too.  Any thoughts?

**Comment by yymao** [comment]
We don't have many tutorials that use butler --- I think the DIA ones will stick to 1.2, and others can move to 2.2i I would say.

**Comment by sschmidt23** [comment]
I just took a pass at updating object_gcr_4_photoz.ipynb to use run2.2i_dr3 rather than run1.2i, added a few plots.  Should I make a separate issue and create a PR for someone to review?  I still want to add a separate tutorial on accessing photo-z's for cosmoDC2v1.1.4_image, as that is a little different.

**Comment by yymao** [comment]
Closing now. July meeting starts in two days, and several notebooks have been updated.
