### ISSUE TITLE
Errors when creating postage stamps based on multiple RA/DEC data points.

### ISSUE THREAD

**Issue by BhairavValera** [LSSTDESC/DC2-analysis#14]
Running a for loop to create multiple images based on given RA/DEC gives me this error:

`NoResults: No locations for get: datasetType:deepCoadd_sub dataId:DataId(initialdata={'tract': 4640, 'patch': '4,5', 'filter': 'r', 'bbox': Box2I(minimum=Point2I(17505, 23067), dimensions=Extent2I(51, 51))}, tag=set())`

The online version also gives a similar error but it was able to elucidate which specific points were causing the error. My code was as such:

```frame = 1
show = False
vmin, vmax = -1.5, +1.5

for objectId, ra, dec in bright_objects_table:
   plt.figure(frame)
   plt.clf()
   make_cutout_image(butler, ra, dec, filter=filter, vmin=vmin, vmax=vmax,
                     label="Object ID: %d" % objectId,
                     show=show)```

**Comment by rmandelb** [comment]
@BhairavValera - is this question associated with your attempt to modify a specific tutorial notebook in this repo?  If so, perhaps you can @ mention the notebook developer in this thread to get their attention?  I am guessing this is related to https://github.com/LSSTDESC/DC2-analysis/blob/master/tutorials/dm_butler_postage_stamps.ipynb and so am tentatively assigning this issue to @wmwv , but please correct me if I am wrong so we can direct the question to the right person.

**Comment by yymao** [comment]
Yes, this is for @wmwv. But I think I may know what's happening after working on the cutout service. I think probably there's just no r-band image for this location. @BhairavValera can you try setting `filter` to `g` to see if it works?

**Comment by BhairavValera** [comment]
@yymao I will try this in a moment and let you know.

**Comment by BhairavValera** [comment]
Okay so changing the band filter works great. Thanks!
