### ISSUE TITLE
Update object catalog from 1.1p to 1.2p/i in tutorial notebooks

### ISSUE THREAD

**Issue by yymao** [LSSTDESC/DC2-analysis#19]
Once the 1.2p object catalog is ready, we need to update object catalog from 1.1p to 1.2p in tutorial notebooks.

Currently this is blocked by the (non-)existence of the 1.2p object catalog. (cc @wmwv).

(cc @reneehlozek as this is one of the hackuDC2 preparation task)

**Comment by reneehlozek** [comment]
Ok, we then just need to update the spreadsheet/confluence pages to make sure folks are on board. There is lots for them to get working on anyway!

**Comment by yymao** [comment]
I'm in the process of updating the relevant tutorial notebooks. I'll create one PR per notebook because some notebooks require more work while others only need trivial changes. Hopefully this would also expedite review process.
