### ISSUE TITLE
Add a tutorial notebook to demonstrate how to access time-varying objects in the truth catalog

### ISSUE THREAD

**Issue by yymao** [LSSTDESC/DC2-analysis#21]
We need a new tutorial notebook to demonstrate how to access time-varying objects in the truth catalog, along the line of https://github.com/LSSTDESC/gcr-catalogs/pull/207

Can someone who know transients better than I do volunteer themselves or promote someone to help with this task (@reneehlozek @wmwv)? 

(cc @reneehlozek as this is one of the hackuDC2 preparation task)

**Comment by reneehlozek** [comment]
hi @yymao, I guess I'm confused, because I'd imagined this might be one of the actual hackurDC2 submissions. What else is needed relative to the one shared above - since it is clear about how to access the catalog?

**Comment by yymao** [comment]
@reneehlozek I was thinking of something that has a bit more science examples, like the HOD example we did for extragalactic catalogs or lensing cut for object catalogs, but it is ok not to have that.

So I'll just copy the example in https://github.com/LSSTDESC/gcr-catalogs/pull/207 and put it into a tutorial notebook. 

(cc @wmwv @rmandelb because there were some offline conversations about this too)

**Comment by yymao** [comment]
Fixed in #25.
