### ISSUE TITLE
Enable beavis-ci on this repo again

### ISSUE THREAD

**Issue by yymao** [LSSTDESC/DC2-analysis#22]
[beavis-ci](https://github.com/LSSTDESC/beavis-ci) has been moved out as a standalone tool, but we should enable it to run on this repo again. And this time maybe let it run on both `tutorials` and `contributed`? (cc @drphilmarshall)

This will also help us to make sure all tutorial notebooks are free of obvious bugs. 

(cc @reneehlozek as this is one of the hackuDC2 preparation task)

**Comment by drphilmarshall** [comment]
I have set this up, reconfiguring my cron job from July. Standalone `beavis-ci` executes every notebook it can find, so as long as the `contributed` folder has a good README.rst file, it should show the badges and links as usual. I only see a markdown file in there for now, though. 

The [README.rst for the `tutorials` folder](https://github.com/LSSTDESC/DC2-analysis/blob/master/tutorials/README.rst) does now show how well we're doing. I see some notebooks failing with missing catalog errors:
```
.beavis/DC2-analysis/tutorials/log/extragalactic_gcr_cluster_colors.log:KeyError: 'Catalog `cosmoDC2_v1.0_small` does not exist in the register. See `available_catalogs`.'
.beavis/DC2-analysis/tutorials/log/extragalactic_gcr_cluster_members.log:KeyError: 'Catalog `cosmoDC2_v1.0_small` doesnot exist in the register. See `available_catalogs`.'
.beavis/DC2-analysis/tutorials/log/extragalactic_gcr_hod.log:KeyError: 'Catalog `cosmoDC2_v1.0_small` does not exist in the register. See `available_catalogs`.'
.beavis/DC2-analysis/tutorials/log/extragalactic_gcr_mass_relations.log:KeyError: 'Catalog `cosmoDC2_v1.0_small` does not exist in the register. See `available_catalogs`.'
.beavis/DC2-analysis/tutorials/log/extragalactic_gcr_redshift_dist.log:KeyError: 'Catalog `cosmoDC2_v1.0_small` does not exist in the register. See `available_catalogs`.'
.beavis/DC2-analysis/tutorials/log/truth_gcr_intro.log:KeyError: 'Catalog `dc2_truth_run1.2_static` does not exist in the register. See `available_catalogs`.'
.beavis/DC2-analysis/tutorials/log/truth_gcr_variables.log:KeyError: 'Catalog `dc2_truth_run1.2_variable_summary` doesnot exist in the register. See `available_catalogs`.'
```
I'm running with the `desc-stack` kernel. If this is as expected, feel free to close this out! Cron will run `beavis-ci` every 6 hours, at 0355, 0955, 1555, 2155 PDT.

**Comment by yymao** [comment]
Many thanks, @drphilmarshall. The failing is due to the shared python env has not been updated with the latest packages. They should go away once Heather updates the shared env. 

I'm closing this now.
