### ISSUE TITLE
Typo found in tutorial

### ISSUE THREAD

**Issue by fjaviersanchez** [LSSTDESC/DC2-analysis#70]
@saurabhwjha found a typo in https://github.com/LSSTDESC/DC2-analysis/blob/master/contributed/cosmoDC2_TheMovie.ipynb

In particular in the line `plt.bar(hp['loc'].bvalues, hp['count'].values, step, color='w', edgecolor='k')` it should be: `plt.bar(hp['loc'].values, hp['count'].values, step, color='w', edgecolor='k')`

I'll go ahead and quickly edit it

**Comment by JulienPeloton** [comment]
Thanks @saurabhwjha for spotting it, and @fjaviersanchez for taking care of it!

**Comment by yymao** [comment]
Closed by #71.
