### ISSUE TITLE
Missing variable definition in TestGalaxyGalaxyLensingSDSSMain.ipynb

### ISSUE THREAD

**Issue by heather999** [LSSTDESC/DC2-analysis#86]
While testing the updated `desc-stack-dev` jupyter kernel, I ran across an error, where `catalog` is undefined:
https://github.com/LSSTDESC/DC2-analysis/blob/c8f2c16e25a45ad9b0c7761401c0d08aed774bc3/contributed/TestGalaxyGalaxyLensingSDSSMain.ipynb#L225
Yao suggests adding: ```catalog = GCRCatalogs.load_catalog('cosmoDC2')```
I'll give that a try and submit a PR.

**Comment by yymao** [comment]
Fixed by #88
