### ISSUE TITLE
Add 'validation' section to 'rendered' branch

### ISSUE THREAD

**Issue by wmwv** [LSSTDESC/DC2-analysis#97]
@yymao I think we should add a `validation` directory for the `rendered` branch

How do we add this to the very-non-continuous integration for Notebooks in DC2-analysis?

Specifically I'd like to add a very memory and disk I/O rendered of validation tests on the Run 2.1 DC2 Object Table.  Do we have a suitable machine to run that on within the non-continuous integration system?

**Comment by yymao** [comment]
> How do we add this to the very-non-continuous integration for Notebooks in DC2-analysis?

Someone who has push permision to `LSSTDESC/DC2-analysis` runs https://github.com/LSSTDESC/beavis-ci on NERSC. 

> Specifically I'd like to add a very memory and disk I/O rendered of validation tests on the Run 2.1 DC2 Object Table. Do we have a suitable machine to run that on within the non-continuous integration system?

What do you mean by "very memory and disk I/O rendered"? Does NERSC work?

**Comment by wmwv** [comment]
> > Specifically I'd like to add a very memory and disk I/O rendered of validation tests on the Run 2.1 DC2 Object Table. Do we have a suitable machine to run that on within the non-continuous integration system?
> 
> What do you mean by "very memory and disk I/O rendered"? Does NERSC work? 

Very memory and disk I/O intensive.  It sometimes works and sometimes doesn't on the JupyterHub node, depending on the overall memory pressure on the node.

**Comment by wmwv** [comment]
OK, so I could, e.g., ask for a reservation on the big-memory node and run there and push.

**Comment by yymao** [comment]
Note that right now if you use `beavis-ci`, you will need to run all notebooks at once and push all of them to `rendered`. I think it would be good to allow partial update to `rendered` but for now you will need to do that on your own.

**Comment by wmwv** [comment]
Manually ran and uploaded Run 1.2p DIA tutorial and Run 2.1i Object Table validation.
